# -*- coding: utf-8 -*-
"""I061_NLP_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eyl6A7rY6zCcNpYWwvRKx-mcgkaQdHKv
"""

import pandas as pd

import numpy as np

import nltk
nltk.download('all')


from nltk import sent_tokenize, word_tokenize

import streamlit as st
from nltk.corpus import stopwords
import re

nltk.download('stopwords')

h=['healthcare','medicine','diagnosis','treatment']
f=['finance','money','cash','investment']
t=['technology','ai','data']
l=['legal','law','defense']

stopWords = set(stopwords.words('english'))
punctuations = {'.', ',', ';', '?', '!'}

def classify_document(text):
    text=text.lower()
    words= word_tokenize(text)
    words = [w for w in words if w not in stopWords]
    words = [w for w in words if w not in punctuations]
    dicth, dictf, dictt, dictl = {}, {}, {}, {}

    for i in words:
        if i in h:
            dicth[i] = dicth.get(i, 0) + 1
        elif i in f:
            dictf[i] = dictf.get(i, 0) + 1
        elif i in t:
            dictt[i] = dictt.get(i, 0) + 1
        elif i in l:
            dictl[i] = dictl.get(i, 0) + 1

    hv = max(dicth.values()) if dicth else 0
    fv = max(dictf.values()) if dictf else 0
    tv = max(dictt.values()) if dictt else 0
    lv = max(dictl.values()) if dictl else 0

    if hv and hv > max(fv, tv, lv):
        return "Document is Healthcare"
    elif fv and fv > max(hv, tv, lv):
        return "Document is Finance"
    elif tv and tv > max(hv, fv, lv):
        return "Document is Technology"
    elif lv and lv > max(hv, fv, tv):
        return "Document is Law"
    else:
        return "No categories matched."

st.title("Document Classification")

user_input = st.text_area("Enter doc")

if st.button("Classify Document"):
    if user_input.strip():
        result = classify_document(user_input)
        st.success(result)
    else:
        st.warning("Enter text doc to classify")

